version: '3.8'
services:
  web:
    build:
      context: .
      #dockerfile: ./migration/to_7.0/Dockerfile
      #dockerfile: ./migration/to_7.1/Dockerfile
      #dockerfile: ./migration/to_7.2/Dockerfile
      #dockerfile: ./migration/to_7.3/Dockerfile
      #dockerfile: ./migration/to_7.4/Dockerfile
      dockerfile: ./migration/to_8.0/Dockerfile
      #dockerfile: ./migration/to_8.1/Dockerfile
      #dockerfile: ./migration/to_8.2/Dockerfile
      #dockerfile: ./migration/to_8.3/Dockerfile
    #ports:
      #- "80:80"
    volumes:
      - .:/var/www/html/
      - ../SmartDoc4:/var/www/html/SmartDoc4
    stdin_open: true # Keep the stdin open
    tty: true # Allocate a pseudo-TTY