version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./migration/to_8.0/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ../SmartDoc4:/var/www/html/SmartDoc4
