version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./migration/to_8.0.2/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - /Users/dprin/Documents/Work/PHPParser:/var/www/html/
      - /Users/dprin/Documents/Work/SmartDoc4:/var/www/html/SmartDoc4