FROM php:7.4-cli

WORKDIR /var/www/html
    
#COPY . .
    
#EXPOSE 80
    
#CMD ["apache2-foreground"]

# Set the entry point to PHP CLI
ENTRYPOINT ["/bin/bash"]
#ENTRYPOINT ["php"]

# Set the default command to run when the container starts
CMD ["-a"]